Resolve mypy issues in 'pie_dial.py'
Get rid of
uwsift/util/widgets/pie_dial.py:155: error: "None" has no attribute "opacity"  [attr-defined]
uwsift/util/widgets/pie_dial.py:181: error: Item "None" of "Optional[PieDial]" has no attribute "opacity"  [union-attr]
uwsift/util/widgets/pie_dial.py:184: error: Item "None" of "Optional[PieDial]" has no attribute "visible"  [union-attr]
uwsift/util/widgets/pie_dial.py:210: error: Item "None" of "Optional[PieDial]" has no attribute "opacity"  [union-attr]
uwsift/util/widgets/pie_dial.py:214: error: Item "None" of "Optional[PieDial]" has no attribute "opacity"  [union-attr]
uwsift/util/widgets/pie_dial.py:334: error: "None" has no attribute "setValue"  [attr-defined]
uwsift/util/widgets/pie_dial.py:335: error: "None" has no attribute "value"  [attr-defined]

by
- making class variable PieDialEditor.pie_dial a member variable
  to avoid the need to intialize it with None
- making SliderPopup._slider a member variable
  to avoid the need to intialize it with None