Get rid of Python2/3 compatibility package 'six'
... since Python 2 is no longer supported.

This also avoids
  error: library stubs not installed for "six"  [import]