Resolve mypy issues in 'tile_calculator.py'
Get rid of

uwsift/view/tile_calculator.py:567: error: Value of type "None" is not indexable  [index]
uwsift/view/tile_calculator.py:568: error: Value of type "None" is not indexable  [index]
uwsift/view/tile_calculator.py:573: error: Value of type "None" is not indexable  [index]
uwsift/view/tile_calculator.py:574: error: Value of type "None" is not indexable  [index]
uwsift/view/tile_calculator.py:575: error: Value of type "None" is not indexable  [index]
uwsift/view/tile_calculator.py:576: error: Value of type "None" is not indexable  [index]

by removing class variables which would be shadowed by member variables
anyway to avoid any need to initialize them with None