Resolve mypy issue in 'metadata_utils.py'
Get rid of
uwsift/workspace/utils/metadata_utils.py:47: error: "Guidebook" has no attribute "default_colormap"  [attr-defined]

by explicitly refering to the only implemented Guidebook sub-class
('ABI_AHI_Guidebook') instead of the base class, because the interface
of the baseclass is underdefined.

TODO: When no other Guidebook than the ABI_AHI_Guidebook is ever
implemented it should be merged into the base class 'Guidebook'.