Resolve mypy issues in 'composite_recipes.py'
uwsift/model/composite_recipes.py:346: error: Module "uuid" is not valid as a type  [valid-type]
uwsift/model/composite_recipes.py:359: error: Argument 2 to "update_rgb_recipe_input_layers" of "RecipeManager" has incompatible type "Optional[str]"; expected "str"  [arg-type]
uwsift/model/composite_recipes.py:359: error: Argument 3 to "update_rgb_recipe_input_layers" of "RecipeManager" has incompatible type "None"; expected "UUID"  [arg-type]
uwsift/model/composite_recipes.py:359: error: Argument 4 to "update_rgb_recipe_input_layers" of "RecipeManager" has incompatible type "Tuple[None, None]"; expected "Tuple[float, float]"  [arg-type]
uwsift/model/composite_recipes.py:362: error: Argument 2 to "update_algebraic_recipe_input_layers" of "RecipeManager" has incompatible type "Optional[str]"; expected "str"  [arg-type]
uwsift/model/composite_recipes.py:362: error: Argument 3 to "update_algebraic_recipe_input_layers" of "RecipeManager" has incompatible type "None"; expected "UUID"  [arg-type]

by
- fine tuning type annotations
- avoiding the possibility, that a dictionary lookup could return None,
  when we now, that ist must succeed (would be a programming bug
  otherwise): just use dict[key] instead of dict.get(key)