Resolve mypy issues in 'queue.py'
Get rid of
uwsift/queue.py:55: error: Need type annotation for "queue"  [var-annotated]
uwsift/queue.py:197: error: "None" has no attribute "pop"  [attr-defined]

by making the class variable in question, 'Worker.queue', a member
variable to avoid the need to intialize it with None and also add a type
annotation to it.

On the occasion make several other class variables of 'Worker' and
'TaskQueue' member variables.