force to grays cmap because fragment shader won't compile on nvidia or older systems. huge performance fix. error on windows nvidia750M:
Internal error: assembly compile error for fragment shader at offset 16332:
-- error message --
line 483, column 7:  error: IF statement nested too deeply.
line 486, column 5:  error: ELSE already found at current nesting level.
line 489, column 7:  error: IF statement nested too deeply.
line 492, column 5:  error: ELSE already found at current nesting level.
line 495, column 7:  error: IF statement nested too deeply.
line 498, column 5:  error: ELSE already found at current nesting level.
line 501, column 7:  error: IF statement nested too deeply.
line 504, column 5:  error: ELSE already found at current nesting level.
line 507, column 7:  error: IF statement nested too deeply.
line 510, column 5:  error: ELSE already found at current nesting level.
line 513, column 7:  error: IF statement nested too deeply.
line 516, column 5:  error: ELSE already found at current nesting level.
line 519, column 7:  error: IF statement nested too deeply.
line 522, column 5:  error: ELSE already
ERROR: Invoking <bound method CspovMainMapCanvas.on_draw of <CspovMainMapCanvas (PyQt4) at 0x71abe48>> for DrawEvent
ERROR:vispy:Invoking <bound method CspovMainMapCanvas.on_draw of <CspovMainMapCanvas (PyQt4) at 0x71abe48>> for DrawEvent
ERROR: Invoking <bound method CspovMainMapCanvas.on_draw of <CspovMainMapCanvas (PyQt4) at 0x71abe48>> repeat 2
ERROR:vispy:Invoking <bound method CspovMainMapCanvas.on_draw of <CspovMainMapCanvas (PyQt4) at 0x71abe48>> repeat 2
ERROR: Invoking <bound method CspovMainMapCanvas.on_draw of <CspovMainMapCanvas (PyQt4) at 0x71abe48>> repeat 4
ERROR:vispy:Invoking <bound method CspovMainMapCanvas.on_draw of <CspovMainMapCanvas (PyQt4) at 0x71abe48>> repeat 4