Fix 2 exceptions in argparser of PsAnalyzer
Positional arguments are always required. Therefore the 'required'
parameter can be removed:

    TypeError: 'required' is an invalid argument for positionals

Rename 'csv-path' to 'input' in order to fix the following exception:

    AttributeError: 'Namespace' object has no attribute 'csv_path'