Resolve mypy issues in 'layer_item.py'
Get rid of

uwsift/model/layer_item.py:50: error: Need type annotation for "_timeline" (hint: "_timeline: Dict[<type>, <type>] = ...")  [var-annotated]
uwsift/model/layer_item.py:85: error: Invalid index type "object" for "Dict[Info, Any]"; expected type "Info"  [index]
uwsift/model/layer_item.py:88: error: Invalid index type "str" for "Dict[Info, Any]"; expected type "Info"  [index]
uwsift/model/layer_item.py:89: error: Invalid index type "str" for "Dict[Info, Any]"; expected type "Info"  [index]
uwsift/model/layer_item.py:91: error: Invalid index type "str" for "Dict[Info, Any]"; expected type "Info"  [index]
uwsift/model/layer_item.py:125: error: Incompatible types in assignment (expression has type "Dict[int, Any]", variable has type "None")  [assignment]
uwsift/model/layer_item.py:137: error: Incompatible types in assignment (expression has type "Dict[int, str]", variable has type "None")  [assignment]
uwsift/model/layer_item.py:138: error: Item "None" of "Optional[Any]" has no attribute "value"  [union-attr]
uwsift/model/layer_item.py:145: error: Unsupported right operand type for in ("None")  [operator]
uwsift/model/layer_item.py:146: error: "None" has no attribute "get"  [attr-defined]
uwsift/model/layer_item.py:334: error: Incompatible return value type (got "None", expected "ProductDataset")  [return-value]
uwsift/model/layer_item.py:337: error: Argument 3 to "get_rgb_multichannel_product_dataset" of "ProductDataset" has incompatible type "Optional[List[UUID]]"; expected "List[UUID]"  [arg-type]
uwsift/model/layer_item.py:337: error: Argument 6 to "get_rgb_multichannel_product_dataset" of "ProductDataset" has incompatible type "Optional[List[frozendict]]"; expected "List[frozendict]"  [arg-type]
uwsift/model/layer_item.py:339: error: Incompatible types in assignment (expression has type "Optional[ProductDataset]", target has type "ProductDataset")  [assignment]
uwsift/model/layer_item.py:341: error: Incompatible return value type (got "Optional[ProductDataset]", expected "ProductDataset")  [return-value]
uwsift/model/layer_item.py:367: error: Argument 4 to "get_algebraic_dataset" of "ProductDataset" has incompatible type "Optional[List[UUID]]"; expected "List[UUID]"  [arg-type]
uwsift/model/layer_item.py:389: error: Item "None" of "Optional[ProductDataset]" has no attribute "uuid"  [union-attr]

by
- fine tuning type annotations
- completing some case distinctions
- avoiding the possibility, that a dictionary lookup could return None,
  when we now, that ist must succeed (would be a programming bug
  otherwise): just use dict[key] instead of dict.get(key)