Fix resampling related exception in auto update mode
... happening in SatpyImporter.

If the auto update mode is active, the 'importer_kwargs' are constructed
in auto_update.py line 133 and used in line 138. In importer.py line 918
the 'resampling_info' can't be found in the kwargs and thus
'self.resampling_info' is set to 'None'.

If the auto update mode isn't active, then the 'resampling_info' is
constructed by the 'update_resampling_info' method in the OpenFileWizard2.

Traceback (most recent call last):
  File "/home/kellerer/Dokumente/eumSIFT/uwsift/queue.py", line 83, in run
    for status in task:
  File "/home/kellerer/Dokumente/eumSIFT/uwsift/__main__.py", line 480, in _bgnd_open_paths
    for progress in self.document.import_files(paths, **importer_kwargs):
  File "/home/kellerer/Dokumente/eumSIFT/uwsift/model/document.py", line 1733, in import_files
    self.activate_product_uuid_as_new_layer(uuid, insert_before=insert_before, **importer_kwargs)
  File "/home/kellerer/Dokumente/eumSIFT/uwsift/model/document.py", line 1587, in activate_product_uuid_as_new_layer
    active_content_data = self._workspace.import_product_content(uuid, **importer_kwargs)
  File "/home/kellerer/Dokumente/eumSIFT/uwsift/workspace/simple_workspace.py", line 318, in import_product_content
    for update in gen:
  File "/home/kellerer/Dokumente/eumSIFT/uwsift/workspace/importer.py", line 1210, in begin_import_products
    resampler: str = self.resampling_info['resampler']
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/kellerer/Dokumente/eumSIFT/uwsift/queue.py", line 193, in _did_complete_task
    todo(succeeded)
  File "/home/kellerer/Dokumente/eumSIFT/uwsift/__main__.py", line 495, in _bgnd_open_paths_finish
    raise ValueError("background open did not succeed")
ValueError: background open did not succeed