Resolve mypy issue in 'workspace.py'
Get rid of

uwsift/workspace/workspace.py:284: error: "dict" is not subscriptable, use "typing.Dict" instead  [misc]

This was wrongly "fixed" in commit
fc24c4b9 ("Resolve mypy issues in '[{caching,simple}_]workspace.py'", 2022-12-29)