Resolve mypy issues in 'importer.py'
Get rid of

-uwsift/workspace/importer.py:174: error: "Guidebook" has no attribute "collect_info"  [attr-defined]
-uwsift/workspace/importer.py:178: error: Argument 2 to "get_default_colormap" has incompatible type "Guidebook"; expected "ABI_AHI_Guidebook"  [arg-type]
-uwsift/workspace/importer.py:181: error: "Guidebook" has no attribute "valid_range"  [attr-defined]
-uwsift/workspace/importer.py:185: error: "Guidebook" has no attribute "_default_display_time"  [attr-defined]
-uwsift/workspace/importer.py:187: error: "Guidebook" has no attribute "_default_display_name"  [attr-defined]
-uwsift/workspace/importer.py:256: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
uwsift/workspace/importer.py:313: error: "aImporter" gets multiple values for keyword argument "workspace_cwd"  [misc]
uwsift/workspace/importer.py:407: error: Return value expected  [return-value]
uwsift/workspace/importer.py:516: error: Incompatible types in assignment (expression has type "dict_values[Any, Any]", variable has type "List[Any]")  [assignment]
uwsift/workspace/importer.py:800: error: Incompatible default for argument "name_prefix" (default has type "None", argument has type "str")  [assignment]
uwsift/workspace/importer.py:800: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/importer.py:800: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/importer.py:833: error: "Guidebook" has no attribute "_default_display_name"  [attr-defined]
uwsift/workspace/importer.py:868: error: Incompatible return value type (got "Dict[Any, Set[Any]]", expected "Dict[str, List[str]]")  [return-value]
uwsift/workspace/importer.py:882: error: Unsupported left operand type for & ("List[str]")  [operator]
uwsift/workspace/importer.py:1214: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
uwsift/workspace/importer.py:1288: error: Need type annotation for "visited_segments" (hint: "visited_segments: List[<type>] = ...")  [var-annotated]

by
- tuning type annotations
- removing class variables which would be shadowed by member variables
  anyway to avoid any need to initialize them with None
- casting a dict.values() result to a list
- replacing references to the base class 'Guidebook' by those to its
  (currently) only sub-class 'ABI_AHI_Guidebook'. This provisionally
  hides the issue, that the base class has not the full interface of the
  sub-class.
  TODO: clean up Guidebook class hierarchy