Resolve mypy issues in 'document.py'
Get rid of

uwsift/model/document.py:71: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
uwsift/model/document.py:72: error: Incompatible types in assignment (expression has type "None", variable has type "TaskQueue")  [assignment]
uwsift/model/document.py:73: error: Incompatible types in assignment (expression has type "None", variable has type "BaseWorkspace")  [assignment]
uwsift/model/document.py:99: error: Need type annotation for "_info_by_uuid" (hint: "_info_by_uuid: Dict[<type>, <type>] = ...")  [var-annotated]
uwsift/model/document.py:204: error: Argument 1 to "dict" has incompatible type "Optional[frozendict]"; expected "SupportsKeysAndGetItem[Any, Any]"  [arg-type]
uwsift/model/document.py:247: error: The return type of a generator function should be "Generator" or one of its supertypes  [misc]

by
- making class variables member variables to avoid any need to
  initialize them with None
- fine tuning type annotations
- revising the way a dict is generated as a copy of a
  Optional[frozendict]

and of

uwsift/model/document.py:282: error: Too many arguments for "find_merge_target" of "BaseWorkspace"  [call-arg]

by fixing the discrepancy of the signature of the
BaseWorkspace.find_merge_target() method compared to the correct
SimpleWorkspace.find_merge_target() one.