Resolve mypy issues in 'scene_graph.py'
... and two remaining ones in '__main__.py'

Get rid of
uwsift/view/scene_graph.py:252: error: Need type annotation for "polygon_probes" (hint: "polygon_probes: Dict[<type>, <type>] = ...")  [var-annotated]
uwsift/view/scene_graph.py:253: error: Need type annotation for "point_probes" (hint: "point_probes: Dict[<type>, <type>] = ...")  [var-annotated]
uwsift/view/scene_graph.py:255: error: Need type annotation for "layer_nodes" (hint: "layer_nodes: Dict[<type>, <type>] = ...")  [var-annotated]
uwsift/view/scene_graph.py:256: error: Need type annotation for "dataset_nodes" (hint: "dataset_nodes: Dict[<type>, <type>] = ...")  [var-annotated]
uwsift/view/scene_graph.py:257: error: Need type annotation for "composite_element_dependencies" (hint: "composite_element_dependencies: Dict[<type>, <type>] = ...")  [var-annotated]
uwsift/view/scene_graph.py:279: error: Incompatible default for argument "borders_shapefiles" (default has type "None", argument has type "List[Any]")  [assignment]
uwsift/view/scene_graph.py:279: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/view/scene_graph.py:279: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/view/scene_graph.py:300: error: Need type annotation for "borders_nodes" (hint: "borders_nodes: List[<type>] = ...")  [var-annotated]
uwsift/view/scene_graph.py:454: error: Item "None" of "Optional[Any]" has no attribute "transforms"  [union-attr]
uwsift/view/scene_graph.py:458: error: Item "None" of "Optional[Any]" has no attribute "camera"  [union-attr]
uwsift/view/scene_graph.py:638: error: Item "None" of "Optional[Any]" has no attribute "native"  [union-attr]
uwsift/view/scene_graph.py:640: error: Item "None" of "Optional[Any]" has no attribute "native"  [union-attr]
uwsift/view/scene_graph.py:642: error: Item "None" of "Optional[Any]" has no attribute "native"  [union-attr]
uwsift/view/scene_graph.py:646: error: Item "None" of "Optional[Any]" has no attribute "events"  [union-attr]
uwsift/view/scene_graph.py:646: error: Item "None" of "Optional[Any]" has no attribute "viewbox_mouse_event"  [union-attr]
uwsift/view/scene_graph.py:647: error: Item "None" of "Optional[Any]" has no attribute "events"  [union-attr]
uwsift/view/scene_graph.py:647: error: Item "None" of "Optional[Any]" has no attribute "viewbox_mouse_event"  [union-attr]
uwsift/view/scene_graph.py:648: error: Item "None" of "Optional[Any]" has no attribute "events"  [union-attr]
uwsift/view/scene_graph.py:648: error: Item "None" of "Optional[Any]" has no attribute "viewbox_mouse_event"  [union-attr]
uwsift/view/scene_graph.py:652: error: Item "None" of "Optional[Any]" has no attribute "events"  [union-attr]
uwsift/view/scene_graph.py:652: error: Item "None" of "Optional[Any]" has no attribute "viewbox_mouse_event"  [union-attr]
uwsift/view/scene_graph.py:653: error: Item "None" of "Optional[Any]" has no attribute "events"  [union-attr]
uwsift/view/scene_graph.py:653: error: Item "None" of "Optional[Any]" has no attribute "viewbox_mouse_event"  [union-attr]
uwsift/view/scene_graph.py:654: error: Item "None" of "Optional[Any]" has no attribute "events"  [union-attr]
uwsift/view/scene_graph.py:654: error: Item "None" of "Optional[Any]" has no attribute "viewbox_mouse_event"  [union-attr]
uwsift/view/scene_graph.py:880: error: Item "None" of "Optional[Any]" has no attribute "find_colormap"  [union-attr]
uwsift/view/scene_graph.py:892: error: Item "None" of "Optional[Any]" has no attribute "get_content"  [union-attr]
uwsift/view/scene_graph.py:932: error: "None" has no attribute "describe_tree"  [attr-defined]
uwsift/view/scene_graph.py:946: error: Item "None" of "Optional[Any]" has no attribute "get_content"  [union-attr]
uwsift/view/scene_graph.py:986: error: "None" has no attribute "describe_tree"  [attr-defined]
uwsift/view/scene_graph.py:993: error: Item "None" of "Optional[Any]" has no attribute "get_content"  [union-attr]
uwsift/view/scene_graph.py:994: error: Item "None" of "Optional[List[UUID]]" has no attribute "__iter__" (not iterable)  [union-attr]
uwsift/view/scene_graph.py:1036: error: "None" has no attribute "describe_tree"  [attr-defined]
uwsift/view/scene_graph.py:1042: error: Item "None" of "Optional[Any]" has no attribute "get_lines_arrays"  [union-attr]
uwsift/view/scene_graph.py:1054: error: "None" has no attribute "describe_tree"  [attr-defined]
uwsift/view/scene_graph.py:1060: error: Item "None" of "Optional[Any]" has no attribute "get_points_arrays"  [union-attr]
uwsift/view/scene_graph.py:1070: error: Item "None" of "Optional[Any]" has no attribute "find_colormap"  [union-attr]
uwsift/view/scene_graph.py:1080: error: "None" has no attribute "describe_tree"  [attr-defined]
uwsift/view/scene_graph.py:1116: error: Item "None" of "Optional[Any]" has no attribute "get_content"  [union-attr]
uwsift/view/scene_graph.py:1117: error: Item "None" of "Optional[List[UUID]]" has no attribute "__iter__" (not iterable)  [union-attr]
uwsift/view/scene_graph.py:1155: error: Item "None" of "Optional[Any]" has no attribute "get_content"  [union-attr]
uwsift/view/scene_graph.py:1211: error: "None" has no attribute "describe_tree"  [attr-defined]
uwsift/view/scene_graph.py:1226: error: "None" has no attribute "describe_tree"  [attr-defined]

uwsift/__main__.py:294: error: Item "None" of "Optional[AnimationController]" has no attribute "animation_speed"  [union-attr]
uwsift/__main__.py:298: error: Item "None" of "Optional[AnimationController]" has no attribute "toggle_animation"  [union-attr]

by
- making some class variables of 'SceneGraphManager' member variables
- adding type annotations
- removing the definition of a few 'SceneGraphManager' member variables
  that reference scene graph nodes from SceneGraphManager.__init__() to
  avoid that they must be initialized with None. They are only defined
  and initialized in other methods.  TODO: This leads to justified
  PyCharm warnings
  "Instance Instance attribute <???> defined outside __init__"
- calming down mypy with assertions that state explicitly, that the
  variables in question cannot be unset