Resolve mypy issues in 'catalogue.py'
Get rid of

uwsift/model/catalogue.py:27: error: Unsupported operand types for + ("str" and "None")  [operator]
uwsift/model/catalogue.py:27: note: Right operand is of type "Optional[Any]"
uwsift/model/catalogue.py:163: error: Incompatible types in assignment (expression has type "None", variable has type "datetime")  [assignment]
uwsift/model/catalogue.py:521: error: Argument 1 to "_expand_to_dict_of_scalars" of "GlobbingCreator" has incompatible type "Optional[List[Dict[Any, Any]]]"; expected "List[Dict[Any, Any]]"  [arg-type]

by preventing variables from becoming None in multiple places, this avoids
the need to use 'Optional[...]' type hints.