Resolve mypy issue in 'importer.py'
Get rid of

uwsift/workspace/importer.py:1259: error: Missing return statement  [return]

and also apply 'black' formatting.

These QA improvements modify code changes introduced with commits
- 62d2f907 ("add error message in case Satpy is outdated", 2023-01-18)
- 3e935f08 ("add optional import of hdf5plugin for reading compressed FCI L1c data", 2023-01-19)
which were created when the pre-commit hooks for black and mypy were not
yet active.

The non-compliances to the QA settings were not noticed when approving
and merging the according merge requests
- !138 ("Update get_fci_segment_height for new padding mechanism in Satpy >= 0.39.0")
  bc0848d4 ("Merge branch 'update_padding_for_FCI' into 'master'", 2023-01-20)
- !139 ("Add optional import of hdf5plugin for reading compressed FCI L1c data")
  9c1b0eee ("Merge branch 'add_hdf5plugin' into 'master'", 2023-01-20)