Fix index error when removing layers from config panes
for Algebraics and RGB Composites. The current implementation throws
an
  IndexError: list index out of range,
due to some kind of iterator invalidation, so, simply, do it right this
time.