Resolve mypy issues in '[{caching,simple}_]workspace.py'
Get rid of

uwsift/workspace/workspace.py:131: error: Incompatible types in assignment (expression has type "Optional[Dict[Any, Any]]", variable has type "Dict[Any, Any]")  [assignment]
uwsift/workspace/workspace.py:255: error: Incompatible types in assignment (expression has type "None", variable has type "Mapping[int, ActiveContent]")  [assignment]
uwsift/workspace/workspace.py:256: error: Incompatible types in assignment (expression has type "None", variable has type "Metadatabase")  [assignment]
uwsift/workspace/workspace.py:271: error: Incompatible types in assignment (expression has type "None", variable has type "Mapping[UUID, Flags]")  [assignment]
uwsift/workspace/workspace.py:294: error: Incompatible default for argument "directory_path" (default has type "None", argument has type "str")  [assignment]
uwsift/workspace/workspace.py:294: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/workspace.py:294: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/workspace.py:306: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/workspace.py:312: error: Cannot determine type of "TheWorkspace"  [has-type]
uwsift/workspace/workspace.py:321: error: Incompatible types in assignment (expression has type "bool", variable has type "None")  [assignment]
uwsift/workspace/workspace.py:361: error: Incompatible default for argument "prod" (default has type "None", argument has type "Product")  [assignment]
uwsift/workspace/workspace.py:361: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/workspace.py:361: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/workspace.py:361: error: Incompatible default for argument "uuid" (default has type "None", argument has type "UUID")  [assignment]
uwsift/workspace/workspace.py:367: error: Incompatible default for argument "prod" (default has type "None", argument has type "Product")  [assignment]
uwsift/workspace/workspace.py:367: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/workspace.py:367: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/workspace.py:367: error: Incompatible default for argument "uuid" (default has type "None", argument has type "UUID")  [assignment]
uwsift/workspace/workspace.py:469: error: Incompatible default for argument "uuid" (default has type "None", argument has type "UUID")  [assignment]
uwsift/workspace/workspace.py:469: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/workspace.py:469: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/workspace.py:470: error: Incompatible default for argument "prod" (default has type "None", argument has type "Product")  [assignment]
uwsift/workspace/workspace.py:470: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/workspace.py:470: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/workspace.py:667: error: Incompatible return value type (got "Tuple[None, None]", expected "Tuple[int, int]")  [return-value]
uwsift/workspace/workspace.py:682: error: Incompatible return value type (got "Tuple[None, None]", expected "Tuple[int, int]")  [return-value]
uwsift/workspace/workspace.py:753: error: Value of type "Optional[Any]" is not indexable  [index]
uwsift/workspace/workspace.py:811: error: Incompatible types in assignment (expression has type "Optional[ActiveContent]", variable has type "ActiveContent")  [assignment]
uwsift/workspace/workspace.py:816: error: Incompatible return value type (got "Optional[Any]", expected "Dict[Any, Any]")  [return-value]
uwsift/workspace/workspace.py:825: error: Incompatible types in assignment (expression has type "Optional[ActiveContent]", variable has type "ActiveContent")  [assignment]
uwsift/workspace/simple_workspace.py:34: error: Incompatible default for argument "directory_path" (default has type "None", argument has type "str")  [assignment]
uwsift/workspace/simple_workspace.py:34: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/simple_workspace.py:34: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/simple_workspace.py:49: error: Incompatible return value type (got "None", expected "Metadatabase")  [return-value]
uwsift/workspace/simple_workspace.py:62: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/simple_workspace.py:81: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/simple_workspace.py:84: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/simple_workspace.py:86: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/simple_workspace.py:92: error: Return type "Optional[Product]" of "_product_with_uuid" incompatible with return type "Product" in supertype "BaseWorkspace"  [override]
uwsift/workspace/simple_workspace.py:96: error: Incompatible default for argument "prod" (default has type "None", argument has type "Product")  [assignment]
uwsift/workspace/simple_workspace.py:96: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/simple_workspace.py:96: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/simple_workspace.py:96: error: Incompatible default for argument "uuid" (default has type "None", argument has type "UUID")  [assignment]
uwsift/workspace/simple_workspace.py:101: error: Incompatible default for argument "prod" (default has type "None", argument has type "Product")  [assignment]
uwsift/workspace/simple_workspace.py:101: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/simple_workspace.py:101: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/simple_workspace.py:101: error: Incompatible default for argument "uuid" (default has type "None", argument has type "UUID")  [assignment]
uwsift/workspace/simple_workspace.py:166: error: Incompatible return value type (got "None", expected "Dict[Any, Any]")  [return-value]
uwsift/workspace/simple_workspace.py:168: error: Missing return statement  [empty-body]
uwsift/workspace/simple_workspace.py:219: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/simple_workspace.py:242: error: Incompatible default for argument "uuid" (default has type "None", argument has type "UUID")  [assignment]
uwsift/workspace/simple_workspace.py:242: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/simple_workspace.py:242: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/simple_workspace.py:243: error: Incompatible default for argument "prod" (default has type "None", argument has type "Product")  [assignment]
uwsift/workspace/simple_workspace.py:243: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/simple_workspace.py:243: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/simple_workspace.py:268: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/simple_workspace.py:372: error: Unsupported right operand type for in ("Info")  [operator]
uwsift/workspace/simple_workspace.py:374: error: No overload variant of "dict" matches argument type "Info"  [call-overload]
uwsift/workspace/simple_workspace.py:374: note: Possible overload variants:
uwsift/workspace/simple_workspace.py:374: note:     def [_KT, _VT] dict(self) -> Dict[_KT, _VT]
uwsift/workspace/simple_workspace.py:374: note:     def [_KT, _VT] dict(self, **kwargs: _VT) -> Dict[str, _VT]
uwsift/workspace/simple_workspace.py:374: note:     def [_KT, _VT] dict(self, SupportsKeysAndGetItem[_KT, _VT], /) -> Dict[_KT, _VT]
uwsift/workspace/simple_workspace.py:374: note:     def [_KT, _VT] dict(self, SupportsKeysAndGetItem[str, _VT], /, **kwargs: _VT) -> Dict[str, _VT]
uwsift/workspace/simple_workspace.py:374: note:     def [_KT, _VT] dict(self, Iterable[Tuple[_KT, _VT]], /) -> Dict[_KT, _VT]
uwsift/workspace/simple_workspace.py:374: note:     def [_KT, _VT] dict(self, Iterable[Tuple[str, _VT]], /, **kwargs: _VT) -> Dict[str, _VT]
uwsift/workspace/simple_workspace.py:374: note:     def [_KT, _VT] dict(self, Iterable[List[str]], /) -> Dict[str, str]
uwsift/workspace/simple_workspace.py:386: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/simple_workspace.py:397: error: Value of type "Info" is not indexable  [index]
uwsift/workspace/simple_workspace.py:398: error: Value of type "Info" is not indexable  [index]
uwsift/workspace/simple_workspace.py:422: error: Argument 1 to "_deactivate_content_for_product" of "SimpleWorkspace" has incompatible type "Optional[Product]"; expected "Product"  [arg-type]
uwsift/workspace/caching_workspace.py:216: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/caching_workspace.py:228: error: Unsupported target for indexed assignment ("Mapping[int, ActiveContent]")  [index]
uwsift/workspace/caching_workspace.py:228: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/caching_workspace.py:251: error: Incompatible default for argument "prod" (default has type "None", argument has type "Product")  [assignment]
uwsift/workspace/caching_workspace.py:251: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/caching_workspace.py:251: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/caching_workspace.py:251: error: Incompatible default for argument "uuid" (default has type "None", argument has type "UUID")  [assignment]
uwsift/workspace/caching_workspace.py:270: error: Incompatible default for argument "prod" (default has type "None", argument has type "Product")  [assignment]
uwsift/workspace/caching_workspace.py:270: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/caching_workspace.py:270: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/caching_workspace.py:270: error: Incompatible default for argument "uuid" (default has type "None", argument has type "UUID")  [assignment]
uwsift/workspace/caching_workspace.py:536: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/caching_workspace.py:550: error: Incompatible default for argument "uuid" (default has type "None", argument has type "UUID")  [assignment]
uwsift/workspace/caching_workspace.py:550: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/caching_workspace.py:550: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/caching_workspace.py:551: error: Incompatible default for argument "prod" (default has type "None", argument has type "Product")  [assignment]
uwsift/workspace/caching_workspace.py:551: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/caching_workspace.py:551: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/caching_workspace.py:570: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/caching_workspace.py:617: error: Unsupported right operand type for in ("Info")  [operator]
uwsift/workspace/caching_workspace.py:619: error: No overload variant of "dict" matches argument type "Info"  [call-overload]
uwsift/workspace/caching_workspace.py:619: note: Possible overload variants:
uwsift/workspace/caching_workspace.py:619: note:     def [_KT, _VT] dict(self) -> Dict[_KT, _VT]
uwsift/workspace/caching_workspace.py:619: note:     def [_KT, _VT] dict(self, **kwargs: _VT) -> Dict[str, _VT]
uwsift/workspace/caching_workspace.py:619: note:     def [_KT, _VT] dict(self, SupportsKeysAndGetItem[_KT, _VT], /) -> Dict[_KT, _VT]
uwsift/workspace/caching_workspace.py:619: note:     def [_KT, _VT] dict(self, SupportsKeysAndGetItem[str, _VT], /, **kwargs: _VT) -> Dict[str, _VT]
uwsift/workspace/caching_workspace.py:619: note:     def [_KT, _VT] dict(self, Iterable[Tuple[_KT, _VT]], /) -> Dict[_KT, _VT]
uwsift/workspace/caching_workspace.py:619: note:     def [_KT, _VT] dict(self, Iterable[Tuple[str, _VT]], /, **kwargs: _VT) -> Dict[str, _VT]
uwsift/workspace/caching_workspace.py:619: note:     def [_KT, _VT] dict(self, Iterable[List[str]], /) -> Dict[str, str]
uwsift/workspace/caching_workspace.py:631: error: Cannot determine type of "cache_dir"  [has-type]
uwsift/workspace/caching_workspace.py:641: error: Value of type "Info" is not indexable  [index]
uwsift/workspace/caching_workspace.py:642: error: Value of type "Info" is not indexable  [index]
uwsift/workspace/caching_workspace.py:720: error: "Mapping[int, ActiveContent]" has no attribute "pop"  [attr-defined]

by
- making some class variables of BaseWorkspace member variables of
  CachingWorkspace, thus move them where they belong and avoid the need
  to initialize them with None
- removing methods from {Base,Simple}Workspace, which are only
  implemented for CachingWorkspace and must not called for the
  SimpleWorkspace anyway
- tuning type annotations
- fixing errorneous type annotations using 'Info' (which is an Enum defined
  in this package) as a type where 'Mapping' is correct
- avoiding default value None for keyword args where possible
- calming down mypy with assertions that state explicityly, that some
  variables in question cannot be unset
- fixing a bug: {}.update({key: value}) does not return anything, i.e.,
  attrs = attrs.update(...) is plain wrong
- avoiding aliasing member variables by local variables