Resolve mypy issues in 'rgb_config.py'
Get rid of

uwsift/view/rgb_config.py:38: error: Incompatible types in assignment (expression has type "None", variable has type "List[Tuple[float, float]]")  [assignment]
uwsift/view/rgb_config.py:44: error: List item 0 has incompatible type "Tuple[None, None]"; expected "Tuple[float, float]"  [list-item]
uwsift/view/rgb_config.py:44: error: List item 1 has incompatible type "Tuple[None, None]"; expected "Tuple[float, float]"  [list-item]
uwsift/view/rgb_config.py:44: error: List item 2 has incompatible type "Tuple[None, None]"; expected "Tuple[float, float]"  [list-item]
uwsift/view/rgb_config.py:45: error: Need type annotation for "_layer_uuids" (hint: "_layer_uuids: List[<type>] = ...")  [var-annotated]
uwsift/view/rgb_config.py:220: error: "None" has no attribute "input_layer_ids"  [attr-defined]
uwsift/view/rgb_config.py:223: error: Item "None" of "Optional[LayerItem]" has no attribute "info"  [union-attr]
uwsift/view/rgb_config.py:233: error: Incompatible default for argument "n" (default has type "None", argument has type "float")  [assignment]
uwsift/view/rgb_config.py:233: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/view/rgb_config.py:233: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/view/rgb_config.py:233: error: Incompatible default for argument "x" (default has type "None", argument has type "float")  [assignment]
uwsift/view/rgb_config.py:267: error: Incompatible default for argument "color" (default has type "None", argument has type "str")  [assignment]
uwsift/view/rgb_config.py:267: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/view/rgb_config.py:267: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/view/rgb_config.py:308: error: Incompatible types in assignment (expression has type "Optional[Recipe]", variable has type "None")  [assignment]
uwsift/view/rgb_config.py:348: error: Incompatible types in assignment (expression has type "Tuple[None, None]", target has type "Tuple[float, float]")  [assignment]
uwsift/view/rgb_config.py:368: error: Item "None" of "Optional[LayerItem]" has no attribute "valid_range"  [union-attr]
uwsift/view/rgb_config.py:370: error: Item "None" of "Optional[LayerItem]" has no attribute "get_actual_range_from_layer"  [union-attr]
uwsift/view/rgb_config.py:439: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]

by
- making class variables member variables to avoid any need to
  initialize them with None
- make optional keywoard arguments mandatory arguments to avoid the need
  to type them as Optional[<type>]
- fine tuning type annotations
- calming down mypy with assertions that states explicityly, that
  variables in question cannot be unset