Resolve mypy issues (except for two) in 'main.py'
Get rid of

uwsift/__main__.py:248: error: Incompatible types in assignment (expression has type "None", variable has type "Document")  [assignment]
uwsift/__main__.py:249: error: Incompatible types in assignment (expression has type "None", variable has type "SceneGraphManager")  [assignment]
uwsift/__main__.py:287: error: Item "None" of "Optional[Any]" has no attribute "animPlayPause"  [union-attr]
uwsift/__main__.py:299: error: Item "None" of "Optional[Any]" has no attribute "animPlayPause"  [union-attr]
uwsift/__main__.py:305: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
uwsift/__main__.py:306: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
uwsift/__main__.py:312: error: Incompatible types in assignment (expression has type "None", variable has type "ResourceSearchPathCollector")  [assignment]
uwsift/__main__.py:491: error: Item "None" of "Optional[Any]" has no attribute "replace"  [union-attr]
uwsift/__main__.py:494: error: Unsupported left operand type for + ("None")  [operator]
uwsift/__main__.py:500: error: Argument 2 to "rename" has incompatible type "None"; expected "Union[str, bytes, PathLike[str], PathLike[bytes]]"  [arg-type]
uwsift/__main__.py:517: error: Item "None" of "Optional[Any]" has no attribute "replace"  [union-attr]
uwsift/__main__.py:1308: error: Syntax error in type annotation  [syntax]
uwsift/__main__.py:1308: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)

by
- making class variables of 'UserControlsAnimation' and 'Main' member
  variables
- adding or fixing type annotations
- avoiding the possibility, that a dictionary lookup could return None,
  when we now, that ist must succeed (would be a programming bug
  otherwise): just use dict[key] instead of dict.get(key)

The following two are not covered, they must be solved elsewhere:
uwsift/__main__.py:294: error: Item "None" of "Optional[AnimationController]" has no attribute "animation_speed"  [union-attr]
uwsift/__main__.py:298: error: Item "None" of "Optional[AnimationController]" has no attribute "toggle_animation"  [union-attr]