Fix `INFO_TO_FIELD` value access
Following error occurred:
    valset = set(cls.INFO_TO_FIELD.values())
AttributeError: 'property' object has no attribute 'values'

The problem here is that INFO_TO_FIELD was declared as property in
commit
d84e2a0c ("Add Content subclasses to metadatabase", 2021-10-11)

However, properties don't work for class members but only for instance
members, but INFO_TO_FIELD is called at other code locations as class
member.