Resolve mypy issues in 'collector.py'
Get rid of

uwsift/workspace/collector.py:65: error: Incompatible types in assignment (expression has type "None", variable has type "BaseWorkspace")  [assignment]
uwsift/workspace/collector.py:66: error: Incompatible types in assignment (expression has type "None", variable has type "List[str]")  [assignment]
uwsift/workspace/collector.py:67: error: Incompatible types in assignment (expression has type "None", variable has type "Mapping[str, datetime]")  [assignment]
uwsift/workspace/collector.py:68: error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
uwsift/workspace/collector.py:69: error: Incompatible types in assignment (expression has type "None", variable has type "bool")  [assignment]
uwsift/workspace/collector.py:70: error: Incompatible types in assignment (expression has type "None", variable has type "List[str]")  [assignment]
uwsift/workspace/collector.py:71: error: Incompatible types in assignment (expression has type "None", variable has type "List[str]")  [assignment]
uwsift/workspace/collector.py:104: error: Incompatible default for argument "dirs" (default has type "None", argument has type "Iterable[str]")  [assignment]
uwsift/workspace/collector.py:104: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
uwsift/workspace/collector.py:104: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
uwsift/workspace/collector.py:136: error: Incompatible types in assignment (expression has type "Union[BaseWorkspace, _workspace_test_proxy]", variable has type "BaseWorkspace")  [assignment]

by
- fixing type annotations
- removing class variables which would be shadowed by member variables
  anyway to avoid any need to initialize them with None
- moving ResourceSearchPathCollector.__init__() to where it belongs (top
  of the class) to make sure typed variable definitions in __init__ are
  seen before any other references to the same variables